import mongoose from "mongoose";

const vendorSchema = new mongoose.Schema(
  {
    userId:       { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    fundraiserId: { type: mongoose.Schema.Types.ObjectId, ref: "Fundraiser", required: true },
    // Denormalised for quick display without joins
    name:  { type: String, required: true, trim: true },
    email: { type: String, required: true, trim: true, lowercase: true },
    // Short referral code (e.g. "AJ47") – generated by admin
    referralCode: { type: String, required: true, trim: true, uppercase: true },
    // Running totals updated each time an order is placed with this vendor's code
    bagsSold:     { type: Number, default: 0, min: 0 },
    totalRevenue: { type: Number, default: 0, min: 0 },
    orderCount:   { type: Number, default: 0, min: 0 },
    revenueGoal:  { type: Number, default: 0, min: 0 },
    isActive:     { type: Boolean, default: true },
  },
  { timestamps: true },
);

// A vendor's referral code must be unique within a fundraiser
vendorSchema.index({ fundraiserId: 1, referralCode: 1 }, { unique: true });

export const Vendor = mongoose.model("Vendor", vendorSchema);
