import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import SiteNav from '../components/SiteNav';

const FEATURES = [
  {
    title: 'Automatic Route Optimization',
    body: 'Routed eliminates hours of manual route planning. Once delivery day arrives, click one button and every driver gets an optimized stop-by-stop route automatically distributed by bag capacity and address proximity.',
  },
  {
    title: 'Mid-Delivery Re-Routing',
    body: 'Life happens on delivery day. If a driver finishes early or falls behind, administrators can re-generate routes with one tap. Completed stops are preserved; remaining stops are intelligently redistributed.',
  },
  {
    title: 'Live Progress Tracking',
    body: 'Administrators watch their entire fleet in real time. Each stop displays a color: red for pending, yellow for current, green for delivered.',
  },
  {
    title: 'Vendor Dashboards',
    body: 'Each vendor (Scout) gets a personal dashboard showing bags sold, total revenue, and a goal progress bar. They can share their unique QR code and referral link to maximize their contribution.',
  },
  {
    title: 'Seamless Customer Ordering',
    body: 'Customers order straight from a fundraiser page without an account. Scan a QR code, pick products, enter a delivery address, and confirm. The whole flow works on any phone or desktop.',
  },
  {
    title: 'OTP Driver Access',
    body: 'Drivers log in with a simple 6-character one-time code. No password to forget or account to maintain. The code is generated by the administrator and expires once the route is complete.',
  },
];

const STATS = [
  { value: 'Any Size', label: 'Organization' },
  { value: '4 Roles', label: 'Admin, Vendor, Driver, Customer' },
  { value: '1-Click', label: 'Route Generation' },
  { value: '100%', label: 'Mobile-First Design' },
];

const LIFECYCLE = [
  { n: '1', title: 'Setup', body: 'Admin creates the fundraiser, adds products, sets dates and contact info.' },
  { n: '2', title: 'Sell', body: 'Vendors share their codes. Customers order online from the fundraiser page.' },
  { n: '3', title: 'Prepare', body: 'Admin adds drivers with bag capacities before delivery day.' },
  { n: '4', title: 'Deliver', body: 'Generate routes with one click. Drivers follow their optimized stop lists.' },
  { n: '5', title: 'Complete', body: 'Delivery finishes. Admin reviews order reports and past fundraiser data.' },
];

export default function About() {
  return (
    <div className="landing-page marketing-dark">
      <SiteNav subpage actionLabel="Login" actionTo="/login" />

      <main className="marketing-page-main">
        <header className="marketing-page-hero">
          <div className="landing-eyebrow">
            <span className="landing-eyebrow-dot" />
            About Routed
          </div>
          <h1>Fundraisers, simplified from first sale to final delivery</h1>
          <p>
            Routed was built for Boy Scouts, Girl Scouts, Cub Scouts, and youth organizations worldwide
            to run more efficient fundraisers, replacing the outdated manual processes that organizers
            have wrestled with for years.
          </p>
        </header>

        <div className="mkt-glass-card mkt-story-card">
          <h2>Why Routed?</h2>
          <p>
            A local Boy Scouts troop runs a mulch fundraiser every year. The hardest part was never the selling.
            It was building the delivery routes. Every year, troop leaders would spend hours manually plotting
            which driver should go where, optimizing by hand on a map. The result was rarely optimal, and the
            process was exhausting before delivery day even began.
          </p>
          <p style={{ marginTop: '.85rem' }}>
            Routed solves that problem completely. Administrators add drivers and their bag capacities, and
            Routed handles the rest: instantly generating optimized routes, tracking delivery progress in real
            time, and allowing re-routing mid-delivery if circumstances change.
          </p>
        </div>

        <div className="mkt-stat-grid">
          {STATS.map(({ value, label }) => (
            <div key={label} className="mkt-glass-card mkt-stat-card">
              <div className="mkt-stat-value">{value}</div>
              <div className="mkt-stat-label">{label}</div>
            </div>
          ))}
        </div>

        <h2 className="mkt-section-title">What Routed Does</h2>
        <div className="mkt-feature-grid">
          {FEATURES.map(({ title, body }) => (
            <div key={title} className="mkt-glass-card mkt-feature-card">
              <h3>{title}</h3>
              <p>{body}</p>
            </div>
          ))}
        </div>

        <h2 className="mkt-section-title">Fundraiser Lifecycle</h2>
        <div className="mkt-timeline">
          {LIFECYCLE.map((step, i, arr) => (
            <div key={step.n} className="mkt-timeline-step">
              <div className="mkt-timeline-rail">
                <div className="mkt-timeline-num">{step.n}</div>
                {i < arr.length - 1 && <div className="mkt-timeline-line" />}
              </div>
              <div className="mkt-timeline-body">
                <strong>{step.title}</strong>
                <p>{step.body}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="mkt-glass-card mkt-callout mkt-callout--green">
          <h3>Privacy &amp; Security</h3>
          <p>
            Routed never stores credit card or banking information. All payment data is handled by a secure third-party processor.
            Customer delivery addresses are encrypted at rest and only accessible to authorized administrators and drivers actively on route.
            Driver OTP codes are single-use and expire after route completion.
          </p>
        </div>

        <div className="mkt-cta-row">
          <Link to="/help" className="glass-btn glass-btn--gold">
            View Help Guide <ArrowRight size={16} />
          </Link>
          <Link to="/request-access" className="glass-btn">
            Request Admin Access <ArrowRight size={16} />
          </Link>
        </div>
      </main>
    </div>
  );
}
