import { Link } from 'react-router-dom';
import SiteNav from '../components/SiteNav';

const FEATURES = [
  {
    icon: '🗺',
    title: 'Automatic Route Optimization',
    body: 'Routed eliminates hours of manual route planning. Once delivery day arrives, click one button and every driver gets an optimized stop-by-stop route automatically distributed by bag capacity and address proximity.',
  },
  {
    icon: '🔄',
    title: 'Mid-Delivery Re-Routing',
    body: 'Life happens on delivery day. If a driver finishes early or falls behind, administrators can re-generate routes with one tap. Completed stops are preserved; remaining stops are intelligently redistributed.',
  },
  {
    icon: '🟢',
    title: 'Live Progress Tracking',
    body: 'Administrators watch their entire fleet in real time. Each stop displays a color — red for pending, yellow for current, green for delivered — so you always know exactly where every driver stands.',
  },
  {
    icon: '📊',
    title: 'Vendor Dashboards',
    body: 'Each vendor (Scout) gets a personal dashboard showing bags sold, total revenue, and a goal progress bar. They can share their unique QR code and referral link to maximize their contribution.',
  },
  {
    icon: '🛒',
    title: 'Seamless Customer Ordering',
    body: 'Customers order straight from a fundraiser page — no account required. Scan a QR code, pick products, enter a delivery address, and confirm. The whole flow works on any phone or desktop.',
  },
  {
    icon: '🔐',
    title: 'OTP Driver Access',
    body: 'Drivers log in with a simple 6-character one-time code — no password to forget or account to maintain. The code is generated by the administrator and expires once the route is complete.',
  },
];

const STATS = [
  { value: 'Any Size', label: 'Organization' },
  { value: '4 Roles', label: 'Admin · Vendor · Driver · Customer' },
  { value: '1-Click', label: 'Route Generation' },
  { value: '100%', label: 'Mobile-First Design' },
];

export default function About() {
  return (
    <div className="marketing-dark">
      <SiteNav subpage actionLabel="Login" actionTo="/login" />

      <main style={{ maxWidth: 860, margin: '0 auto', padding: '6.5rem 1.25rem 5rem' }}>

        {/* Hero */}
        <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
          <span className="title-pill">About Routed</span>
          <h1 style={{ fontFamily: 'var(--serif)', fontSize: 'clamp(2.2rem,5vw,3.4rem)', marginTop: '.75rem', marginBottom: '1rem', lineHeight: 1.15 }}>
            Fundraisers, simplified from first sale to final delivery
          </h1>
          <p style={{ color: 'var(--t3)', lineHeight: 1.75, maxWidth: 640, margin: '0 auto', fontSize: '.97rem' }}>
            Routed was built for Boy Scouts, Girl Scouts, Cub Scouts, and youth organizations worldwide
            to run more efficient fundraisers — replacing the outdated, tedious manual processes that organizers
            have wrestled with for years.
          </p>
        </div>

        {/* Origin Story */}
        <div className="card" style={{ marginBottom: '2rem', padding: '1.75rem', background: 'linear-gradient(135deg,#fffbeb,#fff)' }}>
          <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.45rem', marginBottom: '.75rem' }}>Why Routed?</h2>
          <p style={{ color: 'var(--t2)', lineHeight: 1.75, fontSize: '.95rem' }}>
            A local Boy Scouts troop runs a mulch fundraiser every year. The hardest part was never the selling —
            it was building the delivery routes. Every year, troop leaders would spend hours manually plotting
            which driver should go where, optimizing by hand on a map. The result was rarely optimal, and the
            process was exhausting before delivery day even began.
          </p>
          <p style={{ color: 'var(--t2)', lineHeight: 1.75, fontSize: '.95rem', marginTop: '.85rem' }}>
            Routed solves that problem completely. Administrators add drivers and their bag capacities, and
            Routed handles the rest — instantly generating optimized routes, tracking delivery progress in real
            time, and allowing re-routing mid-delivery if circumstances change.
          </p>
        </div>

        {/* Stats */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '1rem', marginBottom: '2.5rem' }}>
          {STATS.map(({ value, label }) => (
            <div key={label} className="card" style={{ textAlign: 'center', padding: '1.25rem .75rem' }}>
              <div style={{ fontFamily: 'var(--serif)', fontSize: 'clamp(1.3rem,2.5vw,1.8rem)', fontWeight: 800, color: 'var(--gold-dk)', marginBottom: '.3rem' }}>{value}</div>
              <div style={{ fontSize: '.75rem', color: 'var(--t3)', lineHeight: 1.4 }}>{label}</div>
            </div>
          ))}
        </div>

        {/* Features grid */}
        <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.6rem', marginBottom: '1.1rem' }}>What Routed Does</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(260px,1fr))', gap: '.85rem', marginBottom: '2.5rem' }}>
          {FEATURES.map(({ icon, title, body }) => (
            <div key={title} className="card">
              <div style={{ fontSize: '1.8rem', marginBottom: '.6rem' }}>{icon}</div>
              <h3 style={{ fontFamily: 'var(--serif)', fontSize: '1.05rem', marginBottom: '.5rem' }}>{title}</h3>
              <p style={{ color: 'var(--t3)', fontSize: '.875rem', lineHeight: 1.6 }}>{body}</p>
            </div>
          ))}
        </div>

        {/* How it works timeline */}
        <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.6rem', marginBottom: '1.1rem' }}>Fundraiser Lifecycle</h2>
        <div style={{ position: 'relative', marginBottom: '2.5rem' }}>
          {[
            { n: '1', title: 'Setup', body: 'Admin creates the fundraiser, adds products, sets dates and contact info.' },
            { n: '2', title: 'Sell', body: 'Vendors share their codes. Customers order online from the fundraiser page.' },
            { n: '3', title: 'Prepare', body: 'Admin adds drivers with bag capacities before delivery day.' },
            { n: '4', title: 'Deliver', body: 'Generate routes with one click. Drivers follow their optimized stop lists.' },
            { n: '5', title: 'Complete', body: 'Delivery finishes. Admin reviews order reports and past fundraiser data.' },
          ].map((step, i, arr) => (
            <div key={step.n} style={{ display: 'flex', gap: '1.1rem', marginBottom: i < arr.length - 1 ? '1.1rem' : 0 }}>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                <div style={{ width: 36, height: 36, borderRadius: '50%', background: 'var(--gold)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontSize: '.9rem', flexShrink: 0 }}>
                  {step.n}
                </div>
                {i < arr.length - 1 && <div style={{ width: 2, flex: 1, background: 'var(--border-lt)', marginTop: 4 }} />}
              </div>
              <div style={{ paddingBottom: i < arr.length - 1 ? '1.1rem' : 0 }}>
                <p style={{ fontWeight: 700, marginBottom: '.2rem' }}>{step.title}</p>
                <p style={{ color: 'var(--t3)', fontSize: '.9rem' }}>{step.body}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Privacy callout */}
        <div className="card" style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', marginBottom: '2rem' }}>
          <h3 style={{ fontFamily: 'var(--serif)', fontSize: '1.1rem', marginBottom: '.5rem' }}>Privacy &amp; Security</h3>
          <p style={{ color: 'var(--t3)', fontSize: '.9rem', lineHeight: 1.65 }}>
            Routed never stores credit card or banking information. All payment data is handled by a secure third-party processor.
            Customer delivery addresses are encrypted at rest and only accessible to authorized administrators and drivers actively on route.
            Driver OTP codes are single-use and expire after route completion.
          </p>
        </div>

        {/* CTA */}
        <div style={{ textAlign: 'center', display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
          <Link to="/help" className="btn btn-gold btn-lg">View Help Guide</Link>
          <Link to="/request-access" className="btn btn-outline btn-lg">Request Admin Access</Link>
        </div>
      </main>

      <style>{`
        @media(max-width:640px){
          div[style*="repeat(4,1fr)"]{ grid-template-columns: 1fr 1fr !important; }
        }
      `}</style>
    </div>
  );
}
